version: '3'
services:
  caddy:
    image: abiosoft/caddy:latest
    ports:
        -   8080:8080
    command: -root ./nwsync -port 8080 gzip
  nwnxee-server:
    image: beamdog/nwserver:dev
    env_file: ${PWD-.}/config/nwserver.env
    stdin_open: true
    tty: true
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
    restart: always
    ports:
      - "5121:5121/udp"
